server:
  port: 8083

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/micro_database1
    username: abdurrahim
    password: 123456
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
